### ISSUE TITLE
(ruby) GLIb 1.1.2 fails to build with GLib 2.31.20 with ifndef and duplicate enum

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome/ruby-gnome#106]
(ruby) GLib 1.1.2 fails to build with GLib 2.31.20 with

DEBUG: glib-enum-types.c: In function 'g_spawn_error_get_type':
DEBUG: glib-enum-types.c:816:7: error: stray '#' in program
DEBUG: glib-enum-types.c:816:10: error: 'ifndef' undeclared (first use in this function)
DEBUG: glib-enum-types.c:816:10: note: each undeclared identifier is reported only once for each function it appears in
DEBUG: glib-enum-types.c:818:7: error: stray '#' in program
DEBUG: glib-enum-types.c:818:10: error: 'endif' undeclared (first use in this function)
DEBUG: make: **\* [glib-enum-types.o] Error 1

glib-enum-types.c generated by extconf.rb shows:
   803  /\* enumerations from "/usr/include/glib-2.0/glib/gspawn.h" */
   804  GType
   805  g_spawn_error_get_type (void)
   806  {
   807    static GType etype = 0;
   808    if (etype == 0) {
   809      static const GEnumValue values[] = {
   810        { G_SPAWN_ERROR_FORK, "G_SPAWN_ERROR_FORK", "g-spawn-error-fork" },
   811        { G_SPAWN_ERROR_READ, "G_SPAWN_ERROR_READ", "g-spawn-error-read" },
   812        { G_SPAWN_ERROR_CHDIR, "G_SPAWN_ERROR_CHDIR", "g-spawn-error-chdir" },
   813        { G_SPAWN_ERROR_ACCES, "G_SPAWN_ERROR_ACCES", "g-spawn-error-acces" },
   814        { G_SPAWN_ERROR_PERM, "G_SPAWN_ERROR_PERM", "g-spawn-error-perm" },
   815        { G_SPAWN_ERROR_TOO_BIG, "G_SPAWN_ERROR_TOO_BIG", "g-spawn-error-too-big" },
   816        { #ifndef, "#ifndef", "#ifndef" },
   817        { G_SPAWN_ERROR_2BIG, "G_SPAWN_ERROR_2BIG", "g-spawn-error-2big" },
   818        { #endif, "#endif", "#endif" },
   819        { G_SPAWN_ERROR_NOEXEC, "G_SPAWN_ERROR_NOEXEC", "g-spawn-error-noexec" },
   820        { G_SPAWN_ERROR_NAMETOOLONG, "G_SPAWN_ERROR_NAMETOOLONG", "g-spawn-error-nametoolong" },
   821        { G_SPAWN_ERROR_NOENT, "G_SPAWN_ERROR_NOENT", "g-spawn-error-noent" },
   822        { G_SPAWN_ERROR_NOMEM, "G_SPAWN_ERROR_NOMEM", "g-spawn-error-nomem" },
   823        { G_SPAWN_ERROR_NOTDIR, "G_SPAWN_ERROR_NOTDIR", "g-spawn-error-notdir" },
   824        { G_SPAWN_ERROR_LOOP, "G_SPAWN_ERROR_LOOP", "g-spawn-error-loop" },
   825        { G_SPAWN_ERROR_TXTBUSY, "G_SPAWN_ERROR_TXTBUSY", "g-spawn-error-txtbusy" },
   826        { G_SPAWN_ERROR_IO, "G_SPAWN_ERROR_IO", "g-spawn-error-io" },
   827        { G_SPAWN_ERROR_NFILE, "G_SPAWN_ERROR_NFILE", "g-spawn-error-nfile" },
   828        { G_SPAWN_ERROR_MFILE, "G_SPAWN_ERROR_MFILE", "g-spawn-error-mfile" },
   829        { G_SPAWN_ERROR_INVAL, "G_SPAWN_ERROR_INVAL", "g-spawn-error-inval" },
   830        { G_SPAWN_ERROR_ISDIR, "G_SPAWN_ERROR_ISDIR", "g-spawn-error-isdir" },
   831        { G_SPAWN_ERROR_LIBBAD, "G_SPAWN_ERROR_LIBBAD", "g-spawn-error-libbad" },
   832        { G_SPAWN_ERROR_FAILED, "G_SPAWN_ERROR_FAILED", "g-spawn-error-failed" },
   833        { 0, NULL, NULL }
   834      };
   835      etype = g_enum_register_static ("GSpawnError", values);
   836    }
   837    return etype;
   838  }

glib/gspawh.h shows:
    70  typedef enum
    71  {
    72    G_SPAWN_ERROR_FORK,   /\* fork failed due to lack of memory _/
    73    G_SPAWN_ERROR_READ,   /_ read or select on pipes failed _/
    74    G_SPAWN_ERROR_CHDIR,  /_ changing to working dir failed _/
    75    G_SPAWN_ERROR_ACCES,  /_ execv() returned EACCES _/
    76    G_SPAWN_ERROR_PERM,   /_ execv() returned EPERM _/
    77    G_SPAWN_ERROR_TOO_BIG,/_ execv() returned E2BIG _/
    78  #ifndef G_DISABLE_DEPRECATED
    79    G_SPAWN_ERROR_2BIG = G_SPAWN_ERROR_TOO_BIG,
    80  #endif
    81    G_SPAWN_ERROR_NOEXEC, /_ execv() returned ENOEXEC _/
    82    G_SPAWN_ERROR_NAMETOOLONG, /_ ""  "" ENAMETOOLONG _/
    83    G_SPAWN_ERROR_NOENT,       /_ ""  "" ENOENT */
.....
.....
The above #ifndef and intentionally duplicate enum definition was imported with the following commit:
http://git.gnome.org/browse/glib/commit/glib/gspawn.h?id=deea0e39ba6bb7c41da405c1269abb962ca81a71
and it seems that glib_mkenums cannot handle this correctly.

Original report:
https://bugzilla.redhat.com/show_bug.cgi?id=804319
