### ISSUE TITLE
glib2 won't build with GLib 2.31.2

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome/ruby-gnome#65]
glib2 1.0.3 and latest git master won't build with GLib 2.31.2 like

In file included from rbgprivate.h:25:0,
                 from rbglib_win32.c:22:
rbgobject.h:259:0: warning: "G_TYPE_KEY_FILE" redefined [enabled by default]
/usr/include/glib-2.0/gobject/glib-types.h:219:0: note: this is the location of the previous definition
In file included from rbglib_win32.c:24:0:
/usr/include/glib-2.0/glib/gwin32.h:28:2: error: #error "Only <glib.h> can be included directly."
In file included from /usr/include/glib-2.0/glib/gwin32.h:34:0,
                 from rbglib_win32.c:24:
/usr/include/glib-2.0/glib/gtypes.h:28:2: error: #error "Only <glib.h> can be included directly."
make[1]: **\* [rbglib_win32.o] Error 1
make[1]: Leaving directory `/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/ruby-gnome2/glib2/ext/glib2'
make: **\* [all] Error 2

There is some GLib header change which forbids including GLib related header files other than glib.h, see:
http://lists.fedoraproject.org/pipermail/devel/2011-October/158746.html

By the way, there are many warnings about

rbgobject.h:259:0: warning: "G_TYPE_KEY_FILE" redefined [enabled by default]
/usr/include/glib-2.0/gobject/glib-types.h:219:0: note: this is the location of the previous definition

(not only on glib, but also in other components in ruby-gnome2)
