### ISSUE TITLE
ruby-gnome glib 4.1.1 does not compile with glib 2.75.3

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome/ruby-gnome#1547]
With glib 2.75.3 ruby-gnome glib 4.1.1 does not compile with the following error:

```
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. -I/usr/lib64/ruby/vendor_ruby  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -DHAVE_UNISTD_H -DHAVE_RB_CHECK_ARRAY_TYPE -DHAVE_RB_CHECK_HASH_TYPE -DHAVE_RB_EXEC_RECURSIVE -DHAVE_RB_ERRINFO -DHAVE_RB_THREAD_CALL_WITHOUT_GVL -DHAVE_RUBY_NATIVE_THREAD_P -DHAVE_RB_THREAD_CALL_WITH_GVL -DHAVE_RB_GC_REGISTER_MARK_OBJECT -DHAVE_RB_EXC_NEW_STR -DHAVE_RB_ENC_STR_NEW_STATIC -DRUBY_GLIB2_COMPILATION    -fPIC -O2 -flto=3 -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O2 -flto=3 -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  -Wall -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wundef -Wunsafe-loop-optimizations -Wwrite-strings -pthread -pthread -pthread -m64 -o rbglib_bookmarkfile.o -c rbglib_bookmarkfile.c
rbglib_bookmarkfile.c:39:1: error: static declaration of ‘g_bookmark_file_get_type’ follows non-static declaration
   39 | g_bookmark_file_get_type(void)
      | ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gboxed.h:29,
                 from /usr/include/glib-2.0/gobject/gobject.h:31,
                 from /usr/include/glib-2.0/gobject/gbinding.h:31,
                 from /usr/include/glib-2.0/glib-object.h:24,
                 from rbgobject.h:24,
                 from rbgprivate.h:37,
                 from rbglib_bookmarkfile.c:22:
/usr/include/glib-2.0/gobject/glib-types.h:402:9: note: previous declaration of ‘g_bookmark_file_get_type’ with type ‘GType(void)’ {aka ‘long unsigned int(void)’}
  402 | GType   g_bookmark_file_get_type   (void) G_GNUC_CONST;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
rbglib_bookmarkfile.c:50: warning: "G_TYPE_BOOKMARK_FILE" redefined
   50 | #define G_TYPE_BOOKMARK_FILE (g_bookmark_file_get_type())
      | 
/usr/include/glib-2.0/gobject/glib-types.h:337: note: this is the location of the previous definition
  337 | #define G_TYPE_BOOKMARK_FILE (g_bookmark_file_get_type ())
      | 
make: *** [Makefile:249: rbglib_bookmarkfile.o] Error 1
```

I guess this is the following change: `g_bookmark_file_get_type` is now exposed on glib header from 2.75.0:
https://gitlab.gnome.org/GNOME/glib/-/commit/60c935a9c422c6bc0eeb3db3e578cc6ce7cb4133

**Comment by kou** [comment]
Thanks for your report.
Could you try 396d2d3? If it works with GLib 2.75.3, I'll release a new version.

**Comment by mtasaka** [comment]
Confirmed fixed, now compilation succeeds with GLib 2.75.3, thank you.
